# Generated by Django 5.0.4 on 2024-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='unique_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
