# Generated by Django 5.0.4 on 2024-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='unique_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
