# Generated by Django 5.0.4 on 2024-08-31 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_mobile'),
        ('reviews', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skill.coursemodel'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentaccount'),
        ),
    ]
