# Generated by Django 5.0.4 on 2024-09-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='given_by',
            new_name='student-account',
        ),
    ]
