# Generated by Django 5.0.4 on 2024-09-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_unique_id'),
        ('reviews', '0003_rename_given_by_reviewmodel_student_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='student-account',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='given_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_account', to='accounts.studentaccount'),
        ),
    ]
