# Generated by Django 5.0.4 on 2024-10-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='text',
            field=models.CharField(max_length=355),
        ),
    ]
