# Generated by Django 5.0.4 on 2024-08-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('thumbnail', models.ImageField(upload_to='skill/thumbnails')),
                ('paid', models.BooleanField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('approximate_time_to_finish', models.IntegerField(help_text='Time in hours')),
                ('rating', models.FloatField()),
                ('taken_by', models.ManyToManyField(to='accounts.teacheraccount')),
            ],
        ),
    ]
