# Generated by Django 5.0.4 on 2024-08-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
