# Generated by Django 5.0.4 on 2024-09-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_alter_coursemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
