# Generated by Django 5.0.4 on 2024-09-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_alter_coursemodel_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='approximate_time_to_finish',
            new_name='time',
        ),
    ]
