# Generated by Django 5.0.4 on 2024-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_rename_approximate_time_to_finish_coursemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
