# Generated by Django 5.0.4 on 2024-09-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_profile_picture'),
        ('skill', '0005_alter_coursemodel_price_alter_coursemodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='skills',
            field=models.ManyToManyField(to='skill.skillmodel'),
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='taken_by',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='taken_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.teacheraccount'),
        ),
    ]
