# Generated by Django 5.0.4 on 2024-09-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0009_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
