# Generated by Django 5.0.4 on 2024-10-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_skillmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
